### ISSUE TITLE
when_started hook interaction issue with awesome_print

### ISSUE THREAD

**Issue by onyxraven** [pry/pry-stack_explorer#20]
After upgrading to pry 0.10, I started seeing ```when_started hook failed: NoMethodError: private method `eval' called for nil:NilClass /usr/local/opt/rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/pry-stack_explorer-0.4.9.1/lib/pry-stack_explorer.rb:109:in `bindings_equal?'``` after every command.  

I created a new gemfile to test from clean with just

```ruby
source 'https://rubygems.org'
gem 'pry'
gem 'pry-stack_explorer'
```

It did not exhibit the behavior.  After installing awesome_print (as recommended by pry), the error came back.

```
Using awesome_print 1.2.0
Using debug_inspector 0.0.2
Using binding_of_caller 0.7.2
Using coderay 1.1.0
Using method_source 0.8.2
Using slop 3.6.0
Using pry 0.10.1
Using pry-stack_explorer 0.4.9.1
Using bundler 1.6.0
```

I'll follow up with awesome_print as well, but wanted to bring up the error here in case it was an interaction on this side.

**Comment by benzittlau** [comment]
I'm seeing this issue without awesome_print, just a pretty clean pry install with pry-byebug, pry-stack_explorer, and pry_doc:

``` bash
ruby-2.1.5@pryceless_tools ➜  pryceless_tools  pry
[1] pry(main)> show-stack
when_started hook failed: NoMethodError: private method `eval' called for nil:NilClass
/Users/bzittlau/.rvm/gems/ruby-2.1.5@pryceless_tools/gems/pry-stack_explorer-0.4.9.1/lib/pry-stack_explorer.rb:109:in `bindings_equal?'
(see _pry_.hooks.errors to debug)

Showing all accessible frames in stack (7 in total):
--
=> #0  __pry__ <self.__pry__(UNKNOWN) (undefined method)>
   #1 [block]   block in <top (required)>
   #2 [block]   block in parse_options <Pry::CLI.parse_options(args=?)>
   #3 [method]  parse_options <Pry::CLI.parse_options(args=?)>
   #4 [top]     <top (required)>
   #5 [eval]    <main>
   #6 [main]    <main>
```

**Comment by benzittlau** [comment]
Experimenting across some versions of pry and stack_explorer it looks like this is an issue with any => 0.10 version of pry.  It still works for me with the following Gemfile:
```
source 'https://rubygems.org'

gem 'pry', '~> 0.9.12'
gem 'pry-stack_explorer'
```

**Comment by maxkwallace** [comment]
I'm running into this issue with the following:
```
pry (0.10.1)
  * pry-byebug (3.1.0)
  * pry-doc (0.8.0)
  * pry-rails (0.3.4)
  * pry-rescue (1.4.2)
  * pry-stack_explorer (0.4.9.2)
```
No `awesome_print`, or `.pryrc`.

**Comment by aeberlin** [comment]
Also, experiencing the same issue, with same gem + versions as @maxkwallace noted above.

**Comment by aeberlin** [comment]
Follow-up: It seems that `pry-rescue` is auto-requiring `pry-stack_explorer`, regardless of what the Gemfile specified in the `require: foo` setting. I'll investigate more later, but hope this helps other people.

**Comment by taylorannberg** [comment]
Seeing the same thing

**Comment by IronSavior** [comment]
I'm also seeing this with only stack_explorer and rescue plugins.

**Comment by banister** [comment]
Thanks guys, i'll take a look
