### ISSUE TITLE
Stacktrace is always empty with pry-byebug

### ISSUE THREAD

**Issue by GCorbel** [pry/pry-stack_explorer#22]
I use pry-byebug and no matter when I use the command `show-stack`, it's always empty. When I try to do `up`, I have always "Nowhere to go!".

This is the gem list :

    $ gem list | grep pry  
    pry (0.10.1)
    pry-byebug (2.0.0)
    pry-rails (0.3.2)
    pry-stack_explorer (0.4.9.1)

**Comment by GCorbel** [comment]
Here is more information :

`PryStackExplorer.frame_manager(_pry_)` is always nil
`Thread.current[:__pry_frame_managers__][_pry_]` is always an empty array

I have only one value the array `Thread.current[:__pry_frame_managers__]` and this is the backtrace contained : 

	Thread.current[:__pry_frame_managers__].first.first.backtrace
	=> ["/home/dougui/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pry-byebug-2.0.0/lib/pry-byebug/processor.rb:100:in `block in resume_pry'",
	 "/home/dougui/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pry-byebug-2.0.0/lib/pry-byebug/processor.rb:26:in `block in run'",
	 "/home/dougui/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pry-byebug-2.0.0/lib/pry-byebug/processor.rb:25:in `catch'",
	 "/home/dougui/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pry-byebug-2.0.0/lib/pry-byebug/processor.rb:25:in `run'",
	 "/home/dougui/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pry-byebug-2.0.0/lib/pry-byebug/processor.rb:96:in `resume_pry'",
	 "/home/dougui/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/pry-byebug-2.0.0/lib/pry-byebug/processor.rb:57:in `at_line'",
	 "/home/dougui/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/byebug-3.5.1/lib/byebug/context.rb:80:in `at_line'",
	 "/tmp/test.rb:21:in `<main>'"]

**Comment by justin808** [comment]
I'm having the same issue. Using Ruby-2.1.4 and latest versions of:
```
gem "pry"
gem "pry-stack_explorer"
gem 'pry-rails'
gem 'pry-byebug'
```

**Comment by deivid-rodriguez** [comment]
@GCorbel @justin808 `pry-byebug` is incompatible with `pry-stack_explorer` but it provides equivalent functionality built-in.
