### ISSUE TITLE
uninitialized constant PryStackExplorer::Pry

### ISSUE THREAD

**Issue by brchristian** [pry/pry-stack_explorer#30]
If I put `pry-stack_explorer` in my Gemfile, but not `pry` itself, then despite the fact that there is a gemspec dependency on `pry`, I still see errors of the following:

```ruby
/.gem/ruby/2.4.1/gems/bundler-1.15.1/lib/bundler/runtime.rb:85:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'pry-stack_explorer'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant PryStackExplorer::Pry
Backtrace for gem load error is:
/.gem/ruby/2.4.1/gems/pry-stack_explorer-0.4.9.2/lib/pry-stack_explorer/commands.rb:133:in `<module:PryStackExplorer>'
/.gem/ruby/2.4.1/gems/pry-stack_explorer-0.4.9.2/lib/pry-stack_explorer/commands.rb:1:in `<top (required)>'
/.gem/ruby/2.4.1/gems/pry-stack_explorer-0.4.9.2/lib/pry-stack_explorer.rb:5:in `<top (required)>'
/.gem/ruby/2.4.1/gems/bundler-1.15.1/lib/bundler/runtime.rb:82:in `require'
```

My hunch is that there is something happening with load order, and that `pry` needs to be loaded sooner than it is by default.

**Comment by r-obert** [comment]
just add `require 'pry' unless defined?(::Pry)` to pry-stack_explorer.rb and send a PR ;)

**Comment by brchristian** [comment]
@r-obert Submitted #31 :+1:
